//! Apply the portage configuration from a workorder to the worker container.
//!
//! This writes the client's USE flags, `make.conf` settings, `package.use`, etc.
//! into the container's `/etc/portage/` so that emerge produces packages
//! matching the requester's configuration.
//!
//! When cross-compiling, `CHOST` is set to the target and `CBUILD` to the
//! worker's native tuple so that portage knows it's a cross-build.

use std::path::Path;

use anyhow::{Context, Result};
use tokio::fs;
use tracing::info;

use remerge_types::portage::PortageConfig;

/// Apply the full portage configuration to this container.
///
/// `worker_chost` is the build machine's native CHOST (i.e. `CBUILD`).
/// When it differs from the target `CHOST` in `config.make_conf.chost`,
/// we're cross-compiling and need to set both `CHOST` and `CBUILD`.
pub async fn apply_config(
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    write_make_conf(config, worker_chost, gpg_key, gpg_home).await?;
    write_package_use(config).await?;
    write_package_accept_keywords(config).await?;
    write_package_license(config).await?;
    write_package_mask(config).await?;
    write_package_unmask(config).await?;
    write_package_env(config).await?;
    write_env_files(config).await?;
    write_repos_conf(config).await?;
    info!("Portage configuration applied");
    Ok(())
}

/// Write/overwrite `/etc/portage/make.conf` with the client's settings.
///
/// Sets `CHOST` to the target and, when cross-compiling, also `CBUILD`.
async fn write_make_conf(
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    let mc = &config.make_conf;
    let mut content = String::new();

    content.push_str("# Generated by remerge-worker — do not edit.\n\n");

    // ── Target identity ──────────────────────────────────────────────
    content.push_str(&format!("CHOST=\"{}\"\n", mc.chost));

    // If the worker arch differs from the target, set CBUILD so portage
    // knows we're cross-compiling.
    let target_arch = mc.chost.split('-').next().unwrap_or("");
    let worker_arch = worker_chost.split('-').next().unwrap_or("");
    if target_arch != worker_arch {
        content.push_str(&format!("CBUILD=\"{worker_chost}\"\n"));
        info!(
            chost = %mc.chost,
            cbuild = %worker_chost,
            "Cross-compilation detected — setting CHOST and CBUILD"
        );
    }
    content.push('\n');

    // ── Compiler flags (already resolved — no `-march=native`) ───────
    content.push_str(&format!("CFLAGS=\"{}\"\n", mc.cflags));
    content.push_str(&format!("CXXFLAGS=\"{}\"\n", mc.cxxflags));
    content.push_str(&format!("LDFLAGS=\"{}\"\n", mc.ldflags));

    // MAKEOPTS: prefer server-provided parallelism settings (based on the
    // server hardware) over the client's value.  Per-package overrides in
    // package.env are still respected by portage.
    let makeopts = build_makeopts(&mc.makeopts);
    content.push_str(&format!("MAKEOPTS=\"{makeopts}\"\n"));

    if !mc.use_flags.is_empty() {
        if mc.use_flags_resolved {
            // USE flags were fully resolved on the client (profile defaults +
            // make.conf merged via portageq).  Prefix with -* to clear the
            // worker container's own profile defaults — we want EXACTLY the
            // client's resolved set, nothing more.
            content.push_str(&format!("USE=\"-* {}\"\n", mc.use_flags.join(" ")));
        } else {
            // Legacy client: only make.conf USE flags, no profile defaults.
            // Write as-is and hope the worker profile is close enough.
            content.push_str(&format!("USE=\"{}\"\n", mc.use_flags.join(" ")));
        }
    }

    content.push_str(&format!("ACCEPT_LICENSE=\"{}\"\n", mc.accept_license));
    content.push_str(&format!("ACCEPT_KEYWORDS=\"{}\"\n", mc.accept_keywords));

    {
        let mut features = if !mc.features.is_empty() {
            let mut f = mc.features.clone();
            if !f.iter().any(|feat| feat == "buildpkg") {
                f.push("buildpkg".into());
            }
            f
        } else {
            vec!["buildpkg".into(), "noclean".into()]
        };

        // Enable GPG signing if configured by the server.
        if gpg_key.is_some() && gpg_home.is_some() {
            for feat in ["binpkg-signing", "gpg-keepalive"] {
                if !features.iter().any(|f| f == feat) {
                    features.push(feat.into());
                }
            }
        }

        // Strip features that are ineffective in ephemeral containers.
        // ccache: no persistent cache directory mounted.
        // distcc: no distcc daemon configured in the container.
        let before = features.len();
        features.retain(|f| match f.as_str() {
            "ccache" | "distcc" => {
                tracing::warn!(
                    feature = %f,
                    "Stripping FEATURE — not available in ephemeral worker containers"
                );
                false
            }
            _ => true,
        });
        if features.len() < before {
            info!(
                stripped = before - features.len(),
                "Stripped container-incompatible FEATURES"
            );
        }

        content.push_str(&format!("FEATURES=\"{}\"\n", features.join(" ")));
    }

    if !mc.emerge_default_opts.is_empty() {
        content.push_str(&format!(
            "EMERGE_DEFAULT_OPTS=\"{}\"\n",
            mc.emerge_default_opts
        ));
    }

    // ── CPU capability flags (from cpuid2cpuflags) ───────────────────
    if let Some((ref var, ref flags)) = mc.cpu_flags {
        content.push_str(&format!("{var}=\"{}\"\n", flags.join(" ")));
    }

    // ── USE_EXPAND variables ─────────────────────────────────────────
    for (key, values) in &mc.use_expand {
        content.push_str(&format!("{key}=\"{}\"\n", values.join(" ")));
    }

    // ── Extra variables ──────────────────────────────────────────────
    for (key, value) in &mc.extra {
        // Validate key: must be a valid shell variable name
        // (uppercase letters, digits, underscores; must not start with digit).
        if key.is_empty()
            || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            || key.starts_with(|c: char| c.is_ascii_digit())
        {
            tracing::warn!(
                key,
                "Skipping extra make.conf variable with invalid key name"
            );
            continue;
        }

        // Reject values containing shell metacharacters that could be
        // interpreted when make.conf is sourced by bash.
        if value.contains(['`', '$', '\\', '"', '\n', '\r', '\0']) {
            tracing::warn!(key, "Skipping extra make.conf variable with unsafe value");
            continue;
        }
        content.push_str(&format!("{key}=\"{value}\"\n"));
    }

    // Always set PKGDIR so packages go to the mounted volume.
    content.push_str("\n# remerge: output directory for binpkgs\n");
    content.push_str("PKGDIR=\"/var/cache/binpkgs\"\n");

    // ── Binary package OpenPGP signing ────────────────────────────────
    if let (Some(key), Some(home)) = (gpg_key, gpg_home) {
        content.push_str("\n# Binary package OpenPGP signing (injected by remerge-server)\n");
        content.push_str("BINPKG_FORMAT=\"gpkg\"\n");
        content.push_str(&format!("BINPKG_GPG_SIGNING_KEY=\"{key}\"\n"));
        content.push_str(&format!("BINPKG_GPG_SIGNING_GPG_HOME=\"{home}\"\n"));
    }

    fs::write("/etc/portage/make.conf", &content)
        .await
        .context("Failed to write make.conf")?;

    info!("Wrote /etc/portage/make.conf");
    Ok(())
}

/// Write `/etc/portage/package.use/remerge`.
async fn write_package_use(config: &PortageConfig) -> Result<()> {
    if config.package_use.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.use").await?;

    let content: String = config
        .package_use
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.flags.join(" ")))
        .collect();

    fs::write("/etc/portage/package.use/remerge", &content)
        .await
        .context("Failed to write package.use")?;

    info!("Wrote /etc/portage/package.use/remerge");
    Ok(())
}

/// Write `/etc/portage/package.accept_keywords/remerge`.
async fn write_package_accept_keywords(config: &PortageConfig) -> Result<()> {
    if config.package_accept_keywords.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.accept_keywords").await?;

    let content: String = config
        .package_accept_keywords
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.keywords.join(" ")))
        .collect();

    fs::write("/etc/portage/package.accept_keywords/remerge", &content)
        .await
        .context("Failed to write package.accept_keywords")?;

    info!("Wrote /etc/portage/package.accept_keywords/remerge");
    Ok(())
}

/// Write `/etc/portage/package.license/remerge`.
async fn write_package_license(config: &PortageConfig) -> Result<()> {
    if config.package_license.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.license").await?;

    let content: String = config
        .package_license
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.licenses.join(" ")))
        .collect();

    fs::write("/etc/portage/package.license/remerge", &content)
        .await
        .context("Failed to write package.license")?;

    info!("Wrote /etc/portage/package.license/remerge");
    Ok(())
}

/// Write `/etc/portage/package.mask/remerge`.
async fn write_package_mask(config: &PortageConfig) -> Result<()> {
    if config.package_mask.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.mask").await?;

    let content: String = config
        .package_mask
        .iter()
        .map(|atom| format!("{atom}\n"))
        .collect();

    fs::write("/etc/portage/package.mask/remerge", &content)
        .await
        .context("Failed to write package.mask")?;

    info!("Wrote /etc/portage/package.mask/remerge");
    Ok(())
}

/// Write `/etc/portage/package.unmask/remerge`.
async fn write_package_unmask(config: &PortageConfig) -> Result<()> {
    if config.package_unmask.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.unmask").await?;

    let content: String = config
        .package_unmask
        .iter()
        .map(|atom| format!("{atom}\n"))
        .collect();

    fs::write("/etc/portage/package.unmask/remerge", &content)
        .await
        .context("Failed to write package.unmask")?;

    info!("Wrote /etc/portage/package.unmask/remerge");
    Ok(())
}

/// Write `/etc/portage/package.env/remerge`.
///
/// Maps atoms to environment override files (which live in `/etc/portage/env/`).
async fn write_package_env(config: &PortageConfig) -> Result<()> {
    if config.package_env.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/package.env").await?;

    let content: String = config
        .package_env
        .iter()
        .filter(|e| {
            let valid = !e.env_file.trim().is_empty()
                && !e.env_file.contains('/')
                && !e.env_file.contains("..");
            if !valid {
                tracing::warn!(
                    atom = %e.atom,
                    env_file = %e.env_file,
                    "Skipping package.env entry with invalid env_file"
                );
            }
            valid
        })
        .map(|e| format!("{} {}\n", e.atom, e.env_file))
        .collect();

    fs::write("/etc/portage/package.env/remerge", &content)
        .await
        .context("Failed to write package.env")?;

    info!("Wrote /etc/portage/package.env/remerge");
    Ok(())
}

/// Write environment override files to `/etc/portage/env/`.
///
/// These contain per-package variable overrides (e.g. custom CFLAGS,
/// MAKEOPTS, CMAKE_BUILD_TYPE) referenced by `package.env` entries.
async fn write_env_files(config: &PortageConfig) -> Result<()> {
    if config.env_files.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/env").await?;

    for (filename, content) in &config.env_files {
        // Sanitise filename — reject empty, blank, and path-traversal.
        if filename.trim().is_empty() || filename.contains('/') || filename.contains("..") {
            tracing::warn!(filename, "Skipping env file with invalid filename");
            continue;
        }
        let path = format!("/etc/portage/env/{filename}");
        fs::write(&path, content)
            .await
            .with_context(|| format!("Failed to write {path}"))?;
    }

    info!(
        count = config.env_files.len(),
        "Wrote /etc/portage/env/ files"
    );
    Ok(())
}

/// Write portage repository configuration to `/etc/portage/repos.conf/`.
///
/// Forwards the client's repos.conf so the worker knows about custom
/// overlays, sync URIs, and repo priorities.  When the server bind-mounts
/// its repos directory, the repos are already present — these conf files
/// just tell portage where to find them.
async fn write_repos_conf(config: &PortageConfig) -> Result<()> {
    if config.repos_conf.is_empty() {
        return Ok(());
    }

    ensure_dir("/etc/portage/repos.conf").await?;

    for (filename, content) in &config.repos_conf {
        if filename.trim().is_empty() || filename.contains('/') || filename.contains("..") {
            tracing::warn!(filename, "Skipping repos.conf file with invalid filename");
            continue;
        }
        let path = format!("/etc/portage/repos.conf/{filename}");
        fs::write(&path, content)
            .await
            .with_context(|| format!("Failed to write {path}"))?;
    }

    info!(
        count = config.repos_conf.len(),
        "Wrote /etc/portage/repos.conf/ files"
    );
    Ok(())
}

/// Ensure a directory exists (convert file to directory if needed).
async fn ensure_dir(path: &str) -> Result<()> {
    let p = Path::new(path);
    if p.is_file() {
        // Portage supports both file and directory — if it's a file, rename
        // it and create a directory.
        let backup = format!("{path}.bak");
        fs::rename(path, &backup).await?;
        fs::create_dir_all(path).await?;
        // Move the original file into the directory.
        let filename = Path::new(path)
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or("original".into());
        fs::rename(&backup, format!("{path}/{filename}")).await?;
    } else if !p.exists() {
        fs::create_dir_all(path).await?;
    }
    Ok(())
}

/// Build the `MAKEOPTS` value from server-provided env vars, falling back to
/// the client's make.conf value.
///
/// Environment variables checked:
/// - `REMERGE_PARALLEL_JOBS` → `-jN`
/// - `REMERGE_LOAD_AVERAGE` → `-lN`
///
/// Per-package overrides in `package.env` are unaffected — portage applies
/// those on top of the global `MAKEOPTS`.
fn build_makeopts(client_makeopts: &str) -> String {
    let server_jobs = std::env::var("REMERGE_PARALLEL_JOBS").ok();
    let server_load = std::env::var("REMERGE_LOAD_AVERAGE").ok();
    build_makeopts_inner(
        client_makeopts,
        server_jobs.as_deref(),
        server_load.as_deref(),
    )
}

fn build_makeopts_inner(
    client_makeopts: &str,
    server_jobs: Option<&str>,
    server_load: Option<&str>,
) -> String {
    // If neither override is provided, use the client's MAKEOPTS unchanged.
    if server_jobs.is_none() && server_load.is_none() {
        return client_makeopts.to_string();
    }

    // Start from client opts, stripping any existing -j/-l flags.
    let mut parts: Vec<&str> = client_makeopts
        .split_whitespace()
        .filter(|tok| {
            !tok.starts_with("-j")
                && !tok.starts_with("-l")
                && !tok.starts_with("--jobs")
                && !tok.starts_with("--load-average")
        })
        .collect();

    let j_flag;
    if let Some(jobs) = server_jobs {
        j_flag = format!("-j{jobs}");
        parts.push(&j_flag);
        info!(jobs, "Using server-provided parallel jobs");
    }

    let l_flag;
    if let Some(load) = server_load {
        l_flag = format!("-l{load}");
        parts.push(&l_flag);
        info!(load, "Using server-provided load average");
    }

    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use remerge_types::portage::MakeConf;

    #[test]
    fn build_makeopts_no_env() {
        // No overrides — returns client value unchanged.
        assert_eq!(build_makeopts_inner("-j4 -l4.0", None, None), "-j4 -l4.0");
    }

    #[test]
    fn build_makeopts_server_override() {
        let result = build_makeopts_inner("-j4 -l4.0 --quiet", Some("16"), Some("12.0"));
        assert!(result.contains("-j16"));
        assert!(result.contains("-l12.0"));
        assert!(result.contains("--quiet"));
        assert!(!result.contains("-j4"));
    }

    /// Helper: build make.conf content from a `MakeConf` (synchronous wrapper).
    fn make_conf_content(mc: &MakeConf, worker_chost: &str) -> String {
        // Build the content string the same way write_make_conf does,
        // but without actually writing to disk.
        let mut content = String::new();
        content.push_str("# Generated by remerge-worker — do not edit.\n\n");
        content.push_str(&format!("CHOST=\"{}\"\n", mc.chost));
        let target_arch = mc.chost.split('-').next().unwrap_or("");
        let worker_arch = worker_chost.split('-').next().unwrap_or("");
        if target_arch != worker_arch {
            content.push_str(&format!("CBUILD=\"{worker_chost}\"\n"));
        }
        content.push('\n');
        content.push_str(&format!("CFLAGS=\"{}\"\n", mc.cflags));
        content.push_str(&format!("CXXFLAGS=\"{}\"\n", mc.cxxflags));
        content.push_str(&format!("LDFLAGS=\"{}\"\n", mc.ldflags));
        content.push_str(&format!("MAKEOPTS=\"{}\"\n", mc.makeopts));

        if !mc.use_flags.is_empty() {
            if mc.use_flags_resolved {
                content.push_str(&format!("USE=\"-* {}\"\n", mc.use_flags.join(" ")));
            } else {
                content.push_str(&format!("USE=\"{}\"\n", mc.use_flags.join(" ")));
            }
        }
        content
    }

    #[test]
    fn resolved_use_flags_get_star_prefix() {
        let mc = MakeConf {
            use_flags: vec![
                "X".into(),
                "dbus".into(),
                "wayland".into(),
                "-systemd".into(),
            ],
            use_flags_resolved: true,
            ..Default::default()
        };
        let content = make_conf_content(&mc, "x86_64-pc-linux-gnu");
        assert!(
            content.contains("USE=\"-* X dbus wayland -systemd\""),
            "Expected -* prefix for resolved USE flags, got:\n{content}"
        );
    }

    #[test]
    fn unresolved_use_flags_no_star_prefix() {
        let mc = MakeConf {
            use_flags: vec!["X".into(), "wayland".into(), "-systemd".into()],
            use_flags_resolved: false,
            ..Default::default()
        };
        let content = make_conf_content(&mc, "x86_64-pc-linux-gnu");
        assert!(
            content.contains("USE=\"X wayland -systemd\""),
            "Expected no -* prefix for unresolved USE flags, got:\n{content}"
        );
        assert!(
            !content.contains("-*"),
            "Should not contain -* for unresolved flags"
        );
    }
}
