//! Apply the portage configuration from a workorder to the worker container.
//!
//! This writes the client's USE flags, `make.conf` settings, `package.use`, etc.
//! into the container's `/etc/portage/` so that emerge produces packages
//! matching the requester's configuration.
//!
//! When cross-compiling, `CHOST` is set to the target and `CBUILD` to the
//! worker's native tuple so that portage knows it's a cross-build.

use std::path::Path;

use anyhow::{Context, Result};
use tokio::fs;
use tracing::info;

use remerge_types::portage::PortageConfig;

/// Apply the full portage configuration to this container.
///
/// `worker_chost` is the build machine's native CHOST (i.e. `CBUILD`).
/// When it differs from the target `CHOST` in `config.make_conf.chost`,
/// we're cross-compiling and need to set both `CHOST` and `CBUILD`.
pub async fn apply_config(
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    write_make_conf(config, worker_chost, gpg_key, gpg_home).await?;
    write_package_use(config).await?;
    write_package_accept_keywords(config).await?;
    write_package_license(config).await?;
    write_package_mask(config).await?;
    write_package_unmask(config).await?;
    write_package_env(config).await?;
    write_env_files(config).await?;
    write_repos_conf(config).await?;
    write_profile_overlay(config).await?;
    write_patches(config).await?;
    set_profile(config).await?;
    info!("Portage configuration applied");
    Ok(())
}

/// Testable inner variant of [`apply_config`] that writes all portage
/// configuration files relative to `base` (e.g. a temp dir) instead of
/// hardcoded `/etc/portage/`.
///
/// This does NOT call `ensure_repo_locations` or `set_profile`'s
/// on-disk repos.conf scanning, since those operate on absolute
/// container paths.  Profile is set based on repo locations derived
/// from the config's repos_conf.
pub async fn apply_config_inner(
    base: &Path,
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    write_make_conf_inner(base, config, worker_chost, gpg_key, gpg_home).await?;
    write_package_use_inner(base, config).await?;
    write_package_accept_keywords_inner(base, config).await?;
    write_package_license_inner(base, config).await?;
    write_package_mask_inner(base, config).await?;
    write_package_unmask_inner(base, config).await?;
    write_package_env_inner(base, config).await?;
    write_env_files_inner(base, config).await?;
    write_repos_conf_inner(base, config).await?;
    write_profile_overlay_inner(&base.join("profile"), config).await?;
    write_patches_inner(&base.join("patches"), config).await?;

    // Derive repo locations from the config for profile setting.
    let repo_locations: Vec<String> = config
        .repos_conf
        .values()
        .flat_map(|content| parse_repo_sections(content))
        .map(|(_, location)| location)
        .collect();

    set_profile_inner(&config.profile, &repo_locations, &base.join("make.profile")).await?;

    info!(
        "Portage configuration applied to {}",
        base.display()
    );
    Ok(())
}

/// Write/overwrite `/etc/portage/make.conf` with the client's settings.
///
/// Sets `CHOST` to the target and, when cross-compiling, also `CBUILD`.
async fn write_make_conf(
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    write_make_conf_inner(
        Path::new("/etc/portage"),
        config,
        worker_chost,
        gpg_key,
        gpg_home,
    )
    .await
}

/// Testable inner variant of [`write_make_conf`] that writes relative to `base`.
pub async fn write_make_conf_inner(
    base: &Path,
    config: &PortageConfig,
    worker_chost: &str,
    gpg_key: Option<&str>,
    gpg_home: Option<&str>,
) -> Result<()> {
    let mc = &config.make_conf;
    let mut content = String::new();

    content.push_str("# Generated by remerge-worker — do not edit.\n\n");

    // ── Target identity ──────────────────────────────────────────────
    content.push_str(&format!("CHOST=\"{}\"\n", mc.chost));

    // If the worker arch differs from the target, set CBUILD so portage
    // knows we're cross-compiling.
    let target_arch = mc.chost.split('-').next().unwrap_or("");
    let worker_arch = worker_chost.split('-').next().unwrap_or("");
    if target_arch != worker_arch {
        content.push_str(&format!("CBUILD=\"{worker_chost}\"\n"));
        info!(
            chost = %mc.chost,
            cbuild = %worker_chost,
            "Cross-compilation detected — setting CHOST and CBUILD"
        );
    }
    content.push('\n');

    // ── Compiler flags (already resolved — no `-march=native`) ───────
    content.push_str(&format!("CFLAGS=\"{}\"\n", mc.cflags));
    content.push_str(&format!("CXXFLAGS=\"{}\"\n", mc.cxxflags));
    content.push_str(&format!("LDFLAGS=\"{}\"\n", mc.ldflags));

    // MAKEOPTS: prefer server-provided parallelism settings (based on the
    // server hardware) over the client's value.  Per-package overrides in
    // package.env are still respected by portage.
    let makeopts = build_makeopts(&mc.makeopts);
    content.push_str(&format!("MAKEOPTS=\"{makeopts}\"\n"));

    if !mc.use_flags.is_empty() {
        if mc.use_flags_resolved {
            // USE flags were fully resolved on the client (profile defaults +
            // make.conf merged via portageq).  Prefix with -* to clear the
            // worker container's own profile defaults — we want EXACTLY the
            // client's resolved set, nothing more.
            content.push_str(&format!("USE=\"-* {}\"\n", mc.use_flags.join(" ")));
        } else {
            // Legacy client: only make.conf USE flags, no profile defaults.
            // Write as-is and hope the worker profile is close enough.
            content.push_str(&format!("USE=\"{}\"\n", mc.use_flags.join(" ")));
        }
    }

    content.push_str(&format!("ACCEPT_LICENSE=\"{}\"\n", mc.accept_license));
    content.push_str(&format!("ACCEPT_KEYWORDS=\"{}\"\n", mc.accept_keywords));

    {
        let mut features = if !mc.features.is_empty() {
            let mut f = mc.features.clone();
            if !f.iter().any(|feat| feat == "buildpkg") {
                f.push("buildpkg".into());
            }
            f
        } else {
            vec!["buildpkg".into(), "noclean".into()]
        };

        // Enable GPG signing if configured by the server.
        if gpg_key.is_some() && gpg_home.is_some() {
            for feat in ["binpkg-signing", "gpg-keepalive"] {
                if !features.iter().any(|f| f == feat) {
                    features.push(feat.into());
                }
            }
        }

        // Strip features that are ineffective in ephemeral containers.
        // ccache: no persistent cache directory mounted.
        // distcc: no distcc daemon configured in the container.
        let before = features.len();
        features.retain(|f| match f.as_str() {
            "ccache" | "distcc" => {
                tracing::warn!(
                    feature = %f,
                    "Stripping FEATURE — not available in ephemeral worker containers"
                );
                false
            }
            _ => true,
        });
        if features.len() < before {
            info!(
                stripped = before - features.len(),
                "Stripped container-incompatible FEATURES"
            );
        }

        content.push_str(&format!("FEATURES=\"{}\"\n", features.join(" ")));
    }

    if !mc.emerge_default_opts.is_empty() {
        content.push_str(&format!(
            "EMERGE_DEFAULT_OPTS=\"{}\"\n",
            mc.emerge_default_opts
        ));
    }

    // ── CPU capability flags (from cpuid2cpuflags) ───────────────────
    if let Some((ref var, ref flags)) = mc.cpu_flags {
        content.push_str(&format!("{var}=\"{}\"\n", flags.join(" ")));
    }

    // ── USE_EXPAND variables ─────────────────────────────────────────
    for (key, values) in &mc.use_expand {
        content.push_str(&format!("{key}=\"{}\"\n", values.join(" ")));
    }

    // ── Extra variables ──────────────────────────────────────────────
    for (key, value) in &mc.extra {
        // Validate key: must be a valid shell variable name
        // (uppercase letters, digits, underscores; must not start with digit).
        if key.is_empty()
            || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            || key.starts_with(|c: char| c.is_ascii_digit())
        {
            tracing::warn!(
                key,
                "Skipping extra make.conf variable with invalid key name"
            );
            continue;
        }

        // Reject values containing shell metacharacters that could be
        // interpreted when make.conf is sourced by bash.
        if value.contains(['`', '$', '\\', '"', '\n', '\r', '\0']) {
            tracing::warn!(key, "Skipping extra make.conf variable with unsafe value");
            continue;
        }
        content.push_str(&format!("{key}=\"{value}\"\n"));
    }

    // Always set PKGDIR so packages go to the mounted volume.
    content.push_str("\n# remerge: output directory for binpkgs\n");
    content.push_str("PKGDIR=\"/var/cache/binpkgs\"\n");

    // ── Binary package OpenPGP signing ────────────────────────────────
    if let (Some(key), Some(home)) = (gpg_key, gpg_home) {
        content.push_str("\n# Binary package OpenPGP signing (injected by remerge-server)\n");
        content.push_str("BINPKG_FORMAT=\"gpkg\"\n");
        content.push_str(&format!("BINPKG_GPG_SIGNING_KEY=\"{key}\"\n"));
        content.push_str(&format!("BINPKG_GPG_SIGNING_GPG_HOME=\"{home}\"\n"));
    }

    let make_conf_path = base.join("make.conf");
    fs::write(&make_conf_path, &content)
        .await
        .context("Failed to write make.conf")?;

    info!("Wrote {}", make_conf_path.display());
    Ok(())
}

/// Write `/etc/portage/package.use/remerge`.
async fn write_package_use(config: &PortageConfig) -> Result<()> {
    write_package_use_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_use`] that writes relative to `base`.
pub async fn write_package_use_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.package_use.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.use");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_use
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.flags.join(" ")))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.use")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write `/etc/portage/package.accept_keywords/remerge`.
async fn write_package_accept_keywords(config: &PortageConfig) -> Result<()> {
    write_package_accept_keywords_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_accept_keywords`] that writes relative to `base`.
pub async fn write_package_accept_keywords_inner(
    base: &Path,
    config: &PortageConfig,
) -> Result<()> {
    if config.package_accept_keywords.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.accept_keywords");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_accept_keywords
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.keywords.join(" ")))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.accept_keywords")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write `/etc/portage/package.license/remerge`.
async fn write_package_license(config: &PortageConfig) -> Result<()> {
    write_package_license_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_license`] that writes relative to `base`.
pub async fn write_package_license_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.package_license.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.license");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_license
        .iter()
        .map(|e| format!("{} {}\n", e.atom, e.licenses.join(" ")))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.license")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write `/etc/portage/package.mask/remerge`.
async fn write_package_mask(config: &PortageConfig) -> Result<()> {
    write_package_mask_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_mask`] that writes relative to `base`.
pub async fn write_package_mask_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.package_mask.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.mask");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_mask
        .iter()
        .map(|atom| format!("{atom}\n"))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.mask")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write `/etc/portage/package.unmask/remerge`.
async fn write_package_unmask(config: &PortageConfig) -> Result<()> {
    write_package_unmask_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_unmask`] that writes relative to `base`.
pub async fn write_package_unmask_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.package_unmask.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.unmask");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_unmask
        .iter()
        .map(|atom| format!("{atom}\n"))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.unmask")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write `/etc/portage/package.env/remerge`.
///
/// Maps atoms to environment override files (which live in `/etc/portage/env/`).
async fn write_package_env(config: &PortageConfig) -> Result<()> {
    write_package_env_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_package_env`] that writes relative to `base`.
pub async fn write_package_env_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.package_env.is_empty() {
        return Ok(());
    }

    let dir = base.join("package.env");
    fs::create_dir_all(&dir).await?;

    let content: String = config
        .package_env
        .iter()
        .filter(|e| {
            let valid = !e.env_file.trim().is_empty()
                && !e.env_file.contains('/')
                && !e.env_file.contains("..");
            if !valid {
                tracing::warn!(
                    atom = %e.atom,
                    env_file = %e.env_file,
                    "Skipping package.env entry with invalid env_file"
                );
            }
            valid
        })
        .map(|e| format!("{} {}\n", e.atom, e.env_file))
        .collect();

    let path = dir.join("remerge");
    fs::write(&path, &content)
        .await
        .context("Failed to write package.env")?;

    info!("Wrote {}", path.display());
    Ok(())
}

/// Write environment override files to `/etc/portage/env/`.
///
/// These contain per-package variable overrides (e.g. custom CFLAGS,
/// MAKEOPTS, CMAKE_BUILD_TYPE) referenced by `package.env` entries.
async fn write_env_files(config: &PortageConfig) -> Result<()> {
    write_env_files_inner(Path::new("/etc/portage"), config).await
}

/// Testable inner variant of [`write_env_files`] that writes relative to `base`.
pub async fn write_env_files_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.env_files.is_empty() {
        return Ok(());
    }

    let dir = base.join("env");
    fs::create_dir_all(&dir).await?;

    for (filename, content) in &config.env_files {
        // Sanitise filename — reject empty, blank, and path-traversal.
        if filename.trim().is_empty() || filename.contains('/') || filename.contains("..") {
            tracing::warn!(filename, "Skipping env file with invalid filename");
            continue;
        }
        let path = dir.join(filename);
        fs::write(&path, content)
            .await
            .with_context(|| format!("Failed to write {}", path.display()))?;
    }

    info!(
        count = config.env_files.len(),
        "Wrote {} env files",
        dir.display()
    );
    Ok(())
}

/// Write portage repository configuration to `/etc/portage/repos.conf/`.
///
/// Forwards the client's repos.conf so the worker has the same overlay
/// definitions, sync URIs, and repo priorities as the client.  ALL
/// sections are written — the worker's sync step will fetch any repos
/// that aren't already present (e.g. via bind-mount from the server).
///
/// After writing, [`ensure_repo_locations`] creates missing location
/// directories (or symlinks them to bind-mounted repos under
/// `/var/db/repos/`) so portage doesn't error out before sync.
async fn write_repos_conf(config: &PortageConfig) -> Result<()> {
    write_repos_conf_inner(Path::new("/etc/portage"), config).await?;

    // Ensure every referenced repo location exists so portage doesn't
    // error out before we get a chance to sync.
    ensure_repo_locations(config).await?;

    info!(
        count = config.repos_conf.len(),
        "Wrote /etc/portage/repos.conf/ files"
    );
    Ok(())
}

/// Testable inner variant of [`write_repos_conf`] that writes relative to `base`.
///
/// Note: this does NOT call `ensure_repo_locations` — that operates on
/// absolute filesystem paths and is only meaningful inside a container.
pub async fn write_repos_conf_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.repos_conf.is_empty() {
        return Ok(());
    }

    let dir = base.join("repos.conf");
    fs::create_dir_all(&dir).await?;

    for (filename, content) in &config.repos_conf {
        if filename.trim().is_empty() || filename.contains('/') || filename.contains("..") {
            tracing::warn!(filename, "Skipping repos.conf file with invalid filename");
            continue;
        }
        let path = dir.join(filename);
        fs::write(&path, content)
            .await
            .with_context(|| format!("Failed to write {}", path.display()))?;
    }

    Ok(())
}

/// Ensure every repo's `location` directory exists.
///
/// For repos already available under `/var/db/repos/<name>` (bind-mounted
/// from the server), a symlink is created from the repos.conf `location`
/// to the bind-mount path.  For repos not present in the bind-mount, an
/// empty directory is created so `emerge --sync` / `emaint sync` can
/// populate it.
///
/// When repos are bind-mounted read-only (`REMERGE_SKIP_SYNC=1`) and an
/// overlay's location is under `/var/db/repos/` but not present in the
/// mount, the overlay is remapped to a writable path under
/// `/var/tmp/remerge-repos/` and the repos.conf entry is updated.
async fn ensure_repo_locations(config: &PortageConfig) -> Result<()> {
    ensure_repo_locations_inner(
        config,
        Path::new("/var/db/repos"),
        Path::new("/etc/portage/repos.conf"),
        Path::new("/var/tmp/remerge-repos"),
    )
    .await
}

/// Testable inner variant of [`ensure_repo_locations`].
///
/// `repos_base` is where bind-mounted repos live (e.g. `/var/db/repos`).
/// `repos_conf_base` is the directory containing the repos.conf files
/// (e.g. `/etc/portage/repos.conf`).
/// `remap_base` is the writable fallback for read-only repos
/// (e.g. `/var/tmp/remerge-repos`).
pub async fn ensure_repo_locations_inner(
    config: &PortageConfig,
    repos_base: &Path,
    repos_conf_base: &Path,
    remap_base: &Path,
) -> Result<()> {
    use std::path::Component;

    let repos_mounted_ro = std::env::var("REMERGE_SKIP_SYNC").is_ok();

    for (filename, content) in &config.repos_conf {
        for (name, location) in parse_repo_sections(content) {
            // Validate location: must be absolute and contain only
            // normal components (no `..` traversal).
            let loc = Path::new(&location);
            if !loc.is_absolute()
                || loc
                    .components()
                    .any(|c| !matches!(c, Component::RootDir | Component::Normal(_)))
            {
                anyhow::bail!(
                    "Repo '{name}' has invalid location '{location}': \
                     must be an absolute path with no traversal components"
                );
            }

            // Check if the path already exists (use symlink_metadata to
            // detect dangling symlinks too).
            if let Ok(meta) = loc.symlink_metadata() {
                if meta.is_dir() || (meta.is_symlink() && loc.is_dir()) {
                    // Already a directory (or valid symlink to one).
                    continue;
                }
                // Exists but is not a directory — remove it so we can
                // replace with a proper dir or symlink.
                fs::remove_file(loc).await.with_context(|| {
                    format!("Failed to remove non-directory at {location} for repo '{name}'")
                })?;
            }

            // Check if the repo is available under the bind-mount.
            let bind_path = repos_base.join(&name);
            if bind_path.is_dir() {
                if let Some(parent) = loc.parent() {
                    fs::create_dir_all(parent)
                        .await
                        .with_context(|| format!("Failed to create parent dir for {location}"))?;
                }
                tokio::fs::symlink(&bind_path, loc).await.with_context(|| {
                    format!("Failed to symlink {location} → {}", bind_path.display())
                })?;
                info!(
                    repo = %name,
                    location = %location,
                    bind_path = %bind_path.display(),
                    "Symlinked repo location to bind-mounted path"
                );
                continue;
            }

            // Repo not in bind-mount.  If the location is under the
            // read-only mount, remap to a writable alternative path.
            let repos_base_str = repos_base.to_string_lossy();
            let repos_prefix = format!("{repos_base_str}/");
            if repos_mounted_ro && location.starts_with(&repos_prefix) {
                let alt = remap_base.join(&name);
                let alt_str = alt.to_string_lossy().to_string();
                fs::create_dir_all(&alt)
                    .await
                    .with_context(|| format!("Failed to create writable repo dir {alt_str}"))?;
                rewrite_repo_location_inner(repos_conf_base, filename, &location, &alt_str)
                    .await?;
                info!(
                    repo = %name,
                    original = %location,
                    remapped = %alt_str,
                    "Remapped overlay to writable path (bind-mount is read-only)"
                );
            } else {
                // Create an empty directory — will be populated during sync.
                fs::create_dir_all(&location)
                    .await
                    .with_context(|| format!("Failed to create repo directory {location}"))?;
                info!(
                    repo = %name,
                    location = %location,
                    "Created empty repo directory (will sync)"
                );
            }
        }
    }
    Ok(())
}

/// Testable inner variant of `rewrite_repo_location`.
///
/// `repos_conf_base` is the directory containing the repos.conf files
/// (e.g. `/etc/portage/repos.conf`).
pub async fn rewrite_repo_location_inner(
    repos_conf_base: &Path,
    filename: &str,
    old_loc: &str,
    new_loc: &str,
) -> Result<()> {
    let path = repos_conf_base.join(filename);
    let path_str = path.to_string_lossy().to_string();
    let content = fs::read_to_string(&path)
        .await
        .with_context(|| format!("Failed to read {path_str} for location rewrite"))?;

    let mut output = String::with_capacity(content.len());
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some((key, value)) = trimmed.split_once('=')
            && key.trim().eq_ignore_ascii_case("location")
            && value.trim() == old_loc
        {
            output.push_str(&format!("location = {new_loc}\n"));
            continue;
        }
        output.push_str(line);
        output.push('\n');
    }

    fs::write(&path, &output)
        .await
        .with_context(|| format!("Failed to rewrite {path_str}"))?;

    Ok(())
}

/// Write the local profile overlay to `/etc/portage/profile/`.
///
/// This directory overrides profile-level settings (USE masks/forces,
/// package.provided, package.mask at profile level, etc.) without
/// requiring a custom profile.  Files here are layered on top of the
/// selected profile by portage.
async fn write_profile_overlay(config: &PortageConfig) -> Result<()> {
    write_profile_overlay_inner(Path::new("/etc/portage/profile"), config).await
}

pub async fn write_profile_overlay_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.profile_overlay.is_empty() {
        return Ok(());
    }

    for (relative_path, content) in &config.profile_overlay {
        // Validate path components — only allow normal segments (no `..',
        // absolute paths, or other traversal tricks).
        use std::path::Component;
        let has_unsafe_component = std::path::Path::new(relative_path)
            .components()
            .any(|c| !matches!(c, Component::Normal(_)));
        if has_unsafe_component || relative_path.is_empty() {
            tracing::warn!(
                path = %relative_path,
                "Skipping profile overlay file with invalid path"
            );
            continue;
        }

        let full_path = base.join(relative_path);
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent).await.with_context(|| {
                format!(
                    "Failed to create parent dir for profile overlay {}",
                    full_path.display()
                )
            })?;
        }
        fs::write(&full_path, content)
            .await
            .with_context(|| format!("Failed to write profile overlay {}", full_path.display()))?;
    }

    info!(
        count = config.profile_overlay.len(),
        "Wrote profile overlay files into {}",
        base.display()
    );
    Ok(())
}

/// Set the portage profile symlink (`/etc/portage/make.profile`).
///
/// Scans configured repository locations for the profile directory and
/// creates a symlink pointing to it.  This ensures the worker container
/// uses the same profile as the client — affecting USE masks/forces,
/// package masks, system set, and default variable values.
async fn set_profile(config: &PortageConfig) -> Result<()> {
    // Collect repo locations from the on-disk repos.conf, which may have been
    // rewritten by ensure_repo_locations() (e.g. remapping /var/db/repos/…
    // to /var/tmp/remerge-repos/…).  If reading fails, fall back to the
    // in-memory configuration from the workorder.
    let mut repo_locations: Vec<String> = Vec::new();

    if let Ok(mut dir) = fs::read_dir("/etc/portage/repos.conf").await {
        while let Ok(Some(entry)) = dir.next_entry().await {
            let path = entry.path();
            if path.is_file()
                && let Ok(content) = fs::read_to_string(&path).await
            {
                repo_locations.extend(
                    parse_repo_sections(&content)
                        .into_iter()
                        .map(|(_, location)| location),
                );
            }
        }
    }

    // Fall back to the workorder's original repos.conf contents if we
    // could not read any locations from the on-disk files.
    if repo_locations.is_empty() {
        repo_locations = config
            .repos_conf
            .values()
            .flat_map(|content| parse_repo_sections(content))
            .map(|(_, location)| location)
            .collect();
    }

    set_profile_inner(
        &config.profile,
        &repo_locations,
        Path::new("/etc/portage/make.profile"),
    )
    .await
}

pub async fn set_profile_inner(
    profile: &str,
    repo_locations: &[String],
    link_path: &Path,
) -> Result<()> {
    if profile.is_empty() || profile == "unknown" {
        info!("No profile specified — using container default");
        return Ok(());
    }

    // Search for the profile in all configured repos.
    let target = repo_locations
        .iter()
        .map(|loc| format!("{loc}/profiles/{profile}"))
        .find(|p| Path::new(p).is_dir());

    // Fall back to the default gentoo repo location.
    let target = target.unwrap_or_else(|| format!("/var/db/repos/gentoo/profiles/{profile}"));

    if !Path::new(&target).is_dir() {
        tracing::warn!(
            profile = %profile,
            target = %target,
            "Profile directory not found in any repo — keeping container default"
        );
        return Ok(());
    }

    // Remove existing symlink or file.
    if link_path.symlink_metadata().is_ok() {
        if link_path.is_dir() && !link_path.is_symlink() {
            tracing::warn!("make.profile is a real directory — not replacing");
            return Ok(());
        }
        fs::remove_file(link_path).await.ok();
    }

    tokio::fs::symlink(&target, link_path)
        .await
        .with_context(|| format!("Failed to symlink {} → {target}", link_path.display()))?;

    info!(
        profile = %profile,
        target = %target,
        "Set portage profile symlink"
    );
    Ok(())
}

/// Write user patches to `/etc/portage/patches/`.
///
/// These are applied by portage during `src_prepare()` (the user-patch
/// mechanism).  Without them, the worker would build unpatched binaries.
async fn write_patches(config: &PortageConfig) -> Result<()> {
    write_patches_inner(Path::new("/etc/portage/patches"), config).await
}

pub async fn write_patches_inner(base: &Path, config: &PortageConfig) -> Result<()> {
    if config.patches.is_empty() {
        return Ok(());
    }

    for (relative_path, content) in &config.patches {
        // Validate path components — only allow normal segments (no `..',
        // absolute paths, or other traversal tricks).
        use std::path::Component;
        let has_unsafe_component = std::path::Path::new(relative_path)
            .components()
            .any(|c| !matches!(c, Component::Normal(_)));
        if has_unsafe_component || relative_path.is_empty() {
            tracing::warn!(
                path = %relative_path,
                "Skipping patch with invalid path"
            );
            continue;
        }

        let full_path = base.join(relative_path);
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent).await.with_context(|| {
                format!(
                    "Failed to create parent dir for patch {}",
                    full_path.display()
                )
            })?;
        }
        fs::write(&full_path, content)
            .await
            .with_context(|| format!("Failed to write patch {}", full_path.display()))?;
    }

    info!(
        count = config.patches.len(),
        "Wrote patch files to {}",
        base.display()
    );
    Ok(())
}

/// Parse an INI-style repos.conf file and return `(section_name, location)`
/// pairs.  The `[DEFAULT]` section and sections without a `location` key
/// are skipped.
pub fn parse_repo_sections(content: &str) -> Vec<(String, String)> {
    let mut repos = Vec::new();
    let mut current_name = String::new();
    let mut current_location: Option<String> = None;

    let flush = |name: &str, location: Option<String>, out: &mut Vec<(String, String)>| {
        if !name.is_empty()
            && !name.eq_ignore_ascii_case("DEFAULT")
            && let Some(loc) = location
        {
            out.push((name.to_string(), loc));
        }
    };

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            flush(&current_name, current_location.take(), &mut repos);
            current_name = trimmed[1..trimmed.len() - 1].to_string();
        } else if let Some((key, value)) = trimmed.split_once('=')
            && key.trim().eq_ignore_ascii_case("location")
        {
            current_location = Some(value.trim().to_string());
        }
    }
    flush(&current_name, current_location, &mut repos);

    repos
}

/// Build the `MAKEOPTS` value from server-provided env vars, falling back to
/// the client's make.conf value.
///
/// Environment variables checked:
/// - `REMERGE_PARALLEL_JOBS` → `-jN`
/// - `REMERGE_LOAD_AVERAGE` → `-lN`
///
/// Per-package overrides in `package.env` are unaffected — portage applies
/// those on top of the global `MAKEOPTS`.
fn build_makeopts(client_makeopts: &str) -> String {
    let server_jobs = std::env::var("REMERGE_PARALLEL_JOBS").ok();
    let server_load = std::env::var("REMERGE_LOAD_AVERAGE").ok();
    build_makeopts_inner(
        client_makeopts,
        server_jobs.as_deref(),
        server_load.as_deref(),
    )
}

pub fn build_makeopts_inner(
    client_makeopts: &str,
    server_jobs: Option<&str>,
    server_load: Option<&str>,
) -> String {
    // If neither override is provided, use the client's MAKEOPTS unchanged.
    if server_jobs.is_none() && server_load.is_none() {
        return client_makeopts.to_string();
    }

    // Start from client opts, stripping any existing -j/-l flags.
    let mut parts: Vec<&str> = client_makeopts
        .split_whitespace()
        .filter(|tok| {
            !tok.starts_with("-j")
                && !tok.starts_with("-l")
                && !tok.starts_with("--jobs")
                && !tok.starts_with("--load-average")
        })
        .collect();

    let j_flag;
    if let Some(jobs) = server_jobs {
        j_flag = format!("-j{jobs}");
        parts.push(&j_flag);
        info!(jobs, "Using server-provided parallel jobs");
    }

    let l_flag;
    if let Some(load) = server_load {
        l_flag = format!("-l{load}");
        parts.push(&l_flag);
        info!(load, "Using server-provided load average");
    }

    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use remerge_types::portage::{MakeConf, PortageConfig};

    #[test]
    fn build_makeopts_no_env() {
        // No overrides — returns client value unchanged.
        assert_eq!(build_makeopts_inner("-j4 -l4.0", None, None), "-j4 -l4.0");
    }

    #[test]
    fn build_makeopts_server_override() {
        let result = build_makeopts_inner("-j4 -l4.0 --quiet", Some("16"), Some("12.0"));
        assert!(result.contains("-j16"));
        assert!(result.contains("-l12.0"));
        assert!(result.contains("--quiet"));
        assert!(!result.contains("-j4"));
    }

    /// Helper: build make.conf content from a `MakeConf` (synchronous wrapper).
    fn make_conf_content(mc: &MakeConf, worker_chost: &str) -> String {
        // Build the content string the same way write_make_conf does,
        // but without actually writing to disk.
        let mut content = String::new();
        content.push_str("# Generated by remerge-worker — do not edit.\n\n");
        content.push_str(&format!("CHOST=\"{}\"\n", mc.chost));
        let target_arch = mc.chost.split('-').next().unwrap_or("");
        let worker_arch = worker_chost.split('-').next().unwrap_or("");
        if target_arch != worker_arch {
            content.push_str(&format!("CBUILD=\"{worker_chost}\"\n"));
        }
        content.push('\n');
        content.push_str(&format!("CFLAGS=\"{}\"\n", mc.cflags));
        content.push_str(&format!("CXXFLAGS=\"{}\"\n", mc.cxxflags));
        content.push_str(&format!("LDFLAGS=\"{}\"\n", mc.ldflags));
        content.push_str(&format!("MAKEOPTS=\"{}\"\n", mc.makeopts));

        if !mc.use_flags.is_empty() {
            if mc.use_flags_resolved {
                content.push_str(&format!("USE=\"-* {}\"\n", mc.use_flags.join(" ")));
            } else {
                content.push_str(&format!("USE=\"{}\"\n", mc.use_flags.join(" ")));
            }
        }
        content
    }

    #[test]
    fn resolved_use_flags_get_star_prefix() {
        let mc = MakeConf {
            use_flags: vec![
                "X".into(),
                "dbus".into(),
                "wayland".into(),
                "-systemd".into(),
            ],
            use_flags_resolved: true,
            ..Default::default()
        };
        let content = make_conf_content(&mc, "x86_64-pc-linux-gnu");
        assert!(
            content.contains("USE=\"-* X dbus wayland -systemd\""),
            "Expected -* prefix for resolved USE flags, got:\n{content}"
        );
    }

    #[test]
    fn unresolved_use_flags_no_star_prefix() {
        let mc = MakeConf {
            use_flags: vec!["X".into(), "wayland".into(), "-systemd".into()],
            use_flags_resolved: false,
            ..Default::default()
        };
        let content = make_conf_content(&mc, "x86_64-pc-linux-gnu");
        assert!(
            content.contains("USE=\"X wayland -systemd\""),
            "Expected no -* prefix for unresolved USE flags, got:\n{content}"
        );
        assert!(
            !content.contains("-*"),
            "Should not contain -* for unresolved flags"
        );
    }

    #[test]
    fn parse_repo_sections_extracts_names_and_locations() {
        let input = "\
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync

[custom-overlay]
location = /var/lib/layman/custom
sync-type = git
sync-uri = https://example.com/overlay.git
";
        let repos = parse_repo_sections(input);
        assert_eq!(repos.len(), 2);
        assert_eq!(
            repos[0],
            ("gentoo".to_string(), "/var/db/repos/gentoo".to_string())
        );
        assert_eq!(
            repos[1],
            (
                "custom-overlay".to_string(),
                "/var/lib/layman/custom".to_string()
            )
        );
    }

    #[test]
    fn parse_repo_sections_skips_default_and_no_location() {
        let input = "\
[DEFAULT]
main-repo = gentoo

[no-location]
sync-type = git
";
        let repos = parse_repo_sections(input);
        assert!(
            repos.is_empty(),
            "DEFAULT and sections without location should be skipped"
        );
    }

    #[test]
    fn parse_repo_sections_single_section() {
        let input = "[myrepo]\nlocation = /var/db/repos/myrepo\n";
        let repos = parse_repo_sections(input);
        assert_eq!(repos.len(), 1);
        assert_eq!(
            repos[0],
            ("myrepo".to_string(), "/var/db/repos/myrepo".to_string())
        );
    }

    // ── write_profile_overlay_inner ──────────────────────────────────────────

    /// Build a minimal PortageConfig with only `profile_overlay` populated.
    fn config_with_profile_overlay(
        files: impl IntoIterator<Item = (&'static str, &'static str)>,
    ) -> PortageConfig {
        PortageConfig {
            make_conf: MakeConf::default(),
            package_use: vec![],
            package_accept_keywords: vec![],
            package_license: vec![],
            package_mask: vec![],
            package_unmask: vec![],
            package_env: vec![],
            env_files: Default::default(),
            repos_conf: Default::default(),
            patches: Default::default(),
            profile_overlay: files
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            profile: String::new(),
            world: vec![],
        }
    }

    /// Build a minimal PortageConfig with only `patches` populated.
    fn config_with_patches(
        files: impl IntoIterator<Item = (&'static str, &'static str)>,
    ) -> PortageConfig {
        PortageConfig {
            make_conf: MakeConf::default(),
            package_use: vec![],
            package_accept_keywords: vec![],
            package_license: vec![],
            package_mask: vec![],
            package_unmask: vec![],
            package_env: vec![],
            env_files: Default::default(),
            repos_conf: Default::default(),
            patches: files
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            profile_overlay: Default::default(),
            profile: String::new(),
            world: vec![],
        }
    }

    #[tokio::test]
    async fn profile_overlay_rejects_path_traversal() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let config = config_with_profile_overlay([
            ("../escape.conf", "evil"),
            ("/absolute.conf", "evil"),
            ("valid/file.conf", "ok"),
        ]);

        write_profile_overlay_inner(tmp.path(), &config)
            .await
            .expect("should succeed skipping bad paths");

        // Traversal paths must not be created.
        assert!(
            !tmp.path().join("../escape.conf").exists(),
            "traversal path must not be written"
        );
        assert!(
            !tmp.path().join("absolute.conf").exists(),
            "absolute path must not be written"
        );
        // The valid file must be written.
        assert!(
            tmp.path().join("valid/file.conf").exists(),
            "valid relative path must be written"
        );
    }

    #[tokio::test]
    async fn profile_overlay_writes_correct_relative_paths() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let config = config_with_profile_overlay([
            ("package.provided", "dev-libs/foo-1.0\n"),
            ("use.mask", "# no masks\n"),
            ("sub/dir/file", "content\n"),
        ]);

        write_profile_overlay_inner(tmp.path(), &config)
            .await
            .expect("write should succeed");

        assert_eq!(
            std::fs::read_to_string(tmp.path().join("package.provided")).unwrap(),
            "dev-libs/foo-1.0\n"
        );
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("use.mask")).unwrap(),
            "# no masks\n"
        );
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("sub/dir/file")).unwrap(),
            "content\n"
        );
    }

    // ── write_patches_inner ──────────────────────────────────────────────────

    #[tokio::test]
    async fn patches_rejects_path_traversal() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let config = config_with_patches([
            ("../evil.patch", "evil"),
            ("/root.patch", "evil"),
            ("dev-libs/openssl/fix.patch", "--- a\n+++ b\n"),
        ]);

        write_patches_inner(tmp.path(), &config)
            .await
            .expect("should succeed skipping bad paths");

        assert!(
            !tmp.path().join("../evil.patch").exists(),
            "traversal path must not be written"
        );
        assert!(
            !tmp.path().join("root.patch").exists(),
            "absolute path must not be written"
        );
        assert!(
            tmp.path().join("dev-libs/openssl/fix.patch").exists(),
            "valid relative path must be written"
        );
    }

    #[tokio::test]
    async fn patches_writes_correct_relative_paths() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let patch_content = "--- a/file.c\n+++ b/file.c\n@@ -1 +1 @@\n-old\n+new\n";
        let config = config_with_patches([("dev-libs/openssl/fix.patch", patch_content)]);

        write_patches_inner(tmp.path(), &config)
            .await
            .expect("write should succeed");

        assert_eq!(
            std::fs::read_to_string(tmp.path().join("dev-libs/openssl/fix.patch")).unwrap(),
            patch_content,
        );
    }

    // ── set_profile_inner ────────────────────────────────────────────────────

    #[tokio::test]
    async fn set_profile_creates_correct_symlink() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let repo = tmp.path().join("myrepo");
        let profile_dir = repo.join("profiles/default/linux/amd64/23.0");
        std::fs::create_dir_all(&profile_dir).expect("create profile dir");

        let link = tmp.path().join("make.profile");
        let locations = vec![repo.to_string_lossy().into_owned()];

        set_profile_inner("default/linux/amd64/23.0", &locations, &link)
            .await
            .expect("set_profile_inner should succeed");

        assert!(link.is_symlink(), "make.profile must be a symlink");
        assert_eq!(
            std::fs::read_link(&link).unwrap(),
            profile_dir,
            "symlink must point at the profile directory"
        );
    }

    #[tokio::test]
    async fn set_profile_skips_when_profile_not_found() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let link = tmp.path().join("make.profile");
        // No repos have the requested profile.
        let locations: Vec<String> = vec!["/nonexistent/repo".to_string()];

        set_profile_inner("default/linux/amd64/23.0", &locations, &link)
            .await
            .expect("should return Ok even when profile is missing");

        assert!(
            !link.exists(),
            "symlink must not be created when profile dir is absent"
        );
    }

    #[tokio::test]
    async fn set_profile_skips_empty_or_unknown_profile() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let link = tmp.path().join("make.profile");

        set_profile_inner("", &[], &link)
            .await
            .expect("empty profile should return Ok");
        set_profile_inner("unknown", &[], &link)
            .await
            .expect("unknown profile should return Ok");

        assert!(!link.exists(), "no symlink should be created");
    }
}
